### ISSUE TITLE
showNextEvent

### ISSUE THREAD

**Issue by Charly-de** [grenagit/MMM-BiathlonResults#3]
Hi,

I have the problem that as soon as I set `showNextEvent: true`, no ranking list is displayed, only the message "Loading...".
As soon as `showNextEvent: false` or the line is deleted, everything works fine again.

Greetings

**Comment by grenagit** [comment]
Hi @Charly-de,

There was a concern about the format of the data by the API... It seems to be fixed by the latest version I just released!

```
cd ~/MagicMirror/modules/MMM-BiathlonResults
git pull
npm install
```

Thank you for raising the issue :+1:

**Comment by Charly-de** [comment]
Thank you for your quick response
